# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f422a9eb9ba5c53b50e3e00fe0f6a71410d59de7eac2b62408b140343edf209c3da2a54094f77034f05bb75d221eded4b11449866bd44c550e50fa77c0e86285

test:
  secret_key_base: 6e715a5f14b03f6bcbc55876561c2ff2090e42bf25af0c99204f5aa1f421cde7317b63868a34f61139a166abcc6f6f517db7883775aeb8e299f3c53752cf0747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
